@id=6579b001-84cc-4206-8337-d653b46a5b6c

PUT http://localhost:5205/mails/{{id}}
Content-Type: application/json
##and now our request boddy  which we have in Api.md

{
    "name": "Jack Amsterdam",
    "description": "Updated",
    "message": "Updated",
    "startDateTime": "2023-06-04T08:00:00",
    "endDateTime": "2023-06-04T11:00:00",
    "meal": [
        "Oatmeal",
        "Bananas",
        "Strawberries",
        "Salad"
    ]
}