@id=346e9be9-1d46-48cf-a853-2b620938f29e

PUT http://localhost:5205/mails/{{id}}
Content-Type: application/json
##and now our request boddy  which we have in Api.md

{
    "name": "Jack Amsterdam",
    "description": "Updated",
    "message": "Updated",
    "startDateTime": "2023-06-04T08:00:00",
    "endDateTime": "2023-06-04T11:00:00",
    "meal": [
        "Oatmeal",
        "Bananas",
        "Strawberries",
        "Salad"
    ]
}